### GET all localities
GET http://localhost:4003/api/localities

### GET vehicle types
GET http://localhost:4003/api/vehicle-types

### GET stats
GET http://localhost:4003/api/stats

### GET all fares
GET http://localhost:4003/api/fares

### GET fare by id
GET http://localhost:4003/api/fares/1

### Create a new fare
POST http://localhost:4003/api/fares
Content-Type: application/json

{
  "from": "TestTown",
  "to": "OtherTown",
  "vehicleType": "Taxi",
  "price": 55
}

### Update the newly created fare (id 21 expected)
PUT http://localhost:4003/api/fares/21
Content-Type: application/json

{
  "price": 65
}

### Delete the newly created fare (id 21 expected)
DELETE http://localhost:4003/api/fares/21
